### Solicitar todos los boletines
GET http://localhost:3000/boletines

### Solicitud de num, categoria y fecha
GET http://localhost:3000/api/boletines?categoria=avisos

### Recuperar id
GET http://localhost:3000/boletines/5fad6a64-9b0b-42e9-bd0a-f2eb17f70637

###
POST http://localhost:3000/boletines
Content-Type: application/json

{
    "num": "047-03",
    "categoria": "edictos",
    "fecha": "2026-01-25"
}